In [4]:
import pandas as pd
import random
import matplotlib.pyplot as plt
from graphviz import Digraph
from IPython.display import display, Image
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
import os
from sklearn.metrics import mean_squared_error
import plotly.io as pio
pio .renderers.default = 'iframe'

Create Dummy Data

In [7]:
def create_synthetic_data():
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    times = ['Morning', 'Afternoon', 'Evening', 'Night']
    data = {
        'Road Condition': [],
        'Weather Condition': [],
        'Day of the Week': [],
        'Time of Day': [],
        'Number of Lanes': [],
        'Travel Time': []
    }

    for _ in range(100):
        day = random.choice(days)
        time = random.choice(times)
        weather = random.choice([0, 1])  # 0: Clear, 1: Rainy
        lanes = random.randint(1, 5)
        road_condition = random.randint(1, 3)

        # Base travel time
        travel_time = 30

        # Adjust for weekend
        if day in ['Friday', 'Saturday']:
            travel_time -= 5

        # Adjust for weather
        if weather == 1:
            travel_time += 10

        # Adjust for time of day
        if time in ['Morning', 'Afternoon']:
            travel_time += 15

        # Adjust for number of lanes
        travel_time += lanes * 5

        # Add some randomness
        travel_time += random.randint(-5, 5)

        data['Road Condition'].append(road_condition)
        data['Weather Condition'].append(weather)
        data['Day of the Week'].append(day)
        data['Time of Day'].append(time)
        data['Number of Lanes'].append(lanes)
        data['Travel Time'].append(travel_time)

    return pd.DataFrame(data)

In [8]:
df_new = create_synthetic_data()

In [9]:
output_file = "./Data/travel_time_data.csv"
if not os.path.isfile(output_file):
    # Generate the synthetic data
    df = create_synthetic_data()    
    df.to_csv("./Data/travel_time_data.csv", index=False)
else:
    df = pd.read_csv(output_file)

df.head()

,Road Condition,Weather Condition,Day of the Week,Time of Day,Number of Lanes,Travel Time
0,1,1,Thursday,Morning,3,67
1,2,0,Friday,Afternoon,1,45
2,2,0,Tuesday,Evening,3,48
3,2,0,Thursday,Evening,4,53
4,2,1,Wednesday,Evening,5,63

In [10]:
df_new

,Road Condition,Weather Condition,Day of the Week,Time of Day,Number of Lanes,Travel Time
0,3,0,Wednesday,Night,4,47
1,1,1,Thursday,Morning,4,72
2,3,0,Friday,Afternoon,5,68
3,3,0,Tuesday,Night,4,50
4,3,0,Sunday,Morning,3,60
...,...,...,...,...,...,...
95,1,1,Monday,Night,1,47
96,1,1,Sunday,Afternoon,5,76
97,2,1,Tuesday,Afternoon,3,74
98,2,0,Tuesday,Morning,2,59
99,3,0,Friday,Afternoon,4,55

In [11]:
df.describe()

       Road Condition  Weather Condition  Number of Lanes  Travel Time
count      100.000000             100.00       100.000000   100.000000
mean         2.190000               0.55         3.050000    57.630000
std          0.747994               0.50         1.424001    11.010239
min          1.000000               0.00         1.000000    30.000000
25%          2.000000               0.00         2.000000    50.000000
50%          2.000000               1.00         3.000000    58.000000
75%          3.000000               1.00         4.000000    65.000000
max          3.000000               1.00         5.000000    85.000000

**Rule Based Linear Regression**

In [ ]:
def calculate_travel_time (day, time, weather, lanes):
    travel_time = 30
    if day in ['Friday','Saturday']:
        travel_time -= 5
    if weather